import {
  BookOpen,
  Compass,
  FileText,
  Plus,
  Server,
  Settings,
  Terminal,
  Users,
} from 'lucide-react';
import type { CommandItem } from '../ui/command';

export function createCommandRegistry(push: (href: string) => void): CommandItem[] {
  return [
    {
      id: 'app-linshe',
      title: '邻舍.EXE',
      description: '进入邻舍应用延续角色生活与交互',
      category: '应用',
      keywords: ['linshe', '邻舍', 'agent'],
      icon: <Compass className="h-4 w-4" />,
      action: () => push('/apps/linshe'),
    },
    {
      id: 'app-characters',
      title: '角色资料库',
      description: '管理角色设定、外貌、关系与发布版本',
      category: '应用',
      keywords: ['characters', '角色', '人物', 'dossier'],
      icon: <Users className="h-4 w-4" />,
      action: () => push('/apps/characters'),
    },
    {
      id: 'app-notebook',
      title: '创作笔记',
      description: '日记、灵感、世界设定与剧情素材',
      category: '应用',
      keywords: ['notebook', '笔记', '灵感', '日记'],
      icon: <BookOpen className="h-4 w-4" />,
      action: () => push('/apps/notebook'),
    },
    {
      id: 'app-narrative',
      title: '叙事档案',
      description: '任务链阅读、多作品追溯与原文检索',
      category: '应用',
      keywords: ['narrative', '叙事', '剧情', '档案'],
      icon: <FileText className="h-4 w-4" />,
      action: () => push('/apps/narrative'),
    },
    {
      id: 'action-new-character',
      title: '新建角色',
      description: '在角色资料库中创建新角色草稿',
      category: '快捷操作',
      keywords: ['new', 'character', '新建角色'],
      icon: <Plus className="h-4 w-4" />,
      action: () => push('/apps/characters/new'),
    },
    {
      id: 'action-new-note',
      title: '新建笔记',
      description: '随手记录新的灵感或设定',
      category: '快捷操作',
      keywords: ['new', 'note', '新建笔记'],
      icon: <Plus className="h-4 w-4" />,
      action: () => push('/apps/notebook/new'),
    },
    {
      id: 'settings-control-center',
      title: '运行控制中心',
      description: '管理邻舍后端运行栈、服务启停与运行日志',
      category: '设置',
      keywords: ['control center', '控制中心', '运行', '服务', 'runtime'],
      icon: <Server className="h-4 w-4" />,
      action: () => push('/settings/control-center'),
    },
    {
      id: 'settings-public-services',
      title: '公共模型与服务',
      description: '配置 LLM 模型、向量与应用生效模型',
      category: '设置',
      keywords: ['public services', '公共服务', '模型', 'llm', 'provider'],
      icon: <Settings className="h-4 w-4" />,
      action: () => push('/settings/public-services'),
    },
    {
      id: 'action-logs',
      title: '实时日志流',
      description: '查看邻舍与各服务实时输出日志',
      category: '设置',
      keywords: ['logs', '日志', 'stream'],
      icon: <Terminal className="h-4 w-4" />,
      action: () => push('/settings/control-center?tab=logs'),
    },
  ];
}
