'use client';

import Image from 'next/image';
import Link from 'next/link';
import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CharacterDraft, CharacterProfile, CharacterRelationship, CharacterSource, CharacterVersion } from '@sthstart/contracts';
import { adminFetch } from '@/app/lib/admin-fetch';

type Detail = CharacterProfile & { versions: CharacterVersion[]; sources: CharacterSource[]; relationships: CharacterRelationship[]; links: Array<{ app_id: string; local_id: string; source_version: number; local_modified: number }> };
type Section = 'identity' | 'personality' | 'appearance' | 'relations' | 'publish';
const EMPTY: CharacterDraft = { displayName: '', englishName: '', aliases: [], originType: 'original', work: '', world: '', summary: '', identity: '', background: '', currentSituation: '', personality: [], motivations: [], beliefs: [], secrets: [], speech: { tone: '', habits: '', catchphrases: [], examples: [] }, likes: [], dislikes: [], fears: [], boundaries: [], appearance: { description: '', hair: '', eyes: '', build: '', outfits: [], accessories: [] }, extraRules: '' };

async function api<T>(path: string, init?: RequestInit) { const response = await adminFetch(path, { ...init, headers: { 'content-type': 'application/json', ...init?.headers } }); const body = await response.json() as T & { message?: string; error?: string }; if (!response.ok) throw new Error(body.message ?? body.error); return body; }
const lines = (value: string) => value.split(/\r?\n/).map((item) => item.replace(/^[-•]\s*/, '').trim()).filter(Boolean);
const joined = (value: string[]) => value.join('\n');

export function CharacterEditor({ characterId }: { characterId?: string }) {
  const router = useRouter(); const [detail, setDetail] = useState<Detail | null>(null); const [draft, setDraft] = useState<CharacterDraft>(EMPTY); const [tags, setTags] = useState<string[]>([]); const [section, setSection] = useState<Section>('identity');
  const [library, setLibrary] = useState<CharacterProfile[]>([]); const [relationTarget, setRelationTarget] = useState(''); const [relationType, setRelationType] = useState(''); const [relationDescription, setRelationDescription] = useState('');
  const [status, setStatus] = useState<'clean'|'dirty'|'saving'|'saved'|'error'>('clean'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [generating, setGenerating] = useState(false); const [description, setDescription] = useState(''); const avatarInput = useRef<HTMLInputElement>(null); const importInput = useRef<HTMLInputElement>(null);
  const currentId = useRef(characterId);
  const load = async (id: string) => { const value = await api<Detail>(`characters/${id}`); setDetail(value); setDraft(value.draft); setTags(value.tags); setStatus('clean'); };
  useEffect(() => { void Promise.all([api<{ items: CharacterProfile[] }>('characters'), characterId ? api<Detail>(`characters/${characterId}`) : Promise.resolve(null)]).then(([characters, value]) => { setLibrary(characters.items); if (value) { setDetail(value); setDraft(value.draft); setTags(value.tags); setStatus('clean'); } }).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [characterId]);
  useEffect(() => { if (!currentId.current || status !== 'dirty') return; const timer = setTimeout(() => void save(true), 850); return () => clearTimeout(timer); }, [draft, tags, status]); // eslint-disable-line react-hooks/exhaustive-deps
  const change = (patch: Partial<CharacterDraft>) => { setDraft((current) => ({ ...current, ...patch })); setStatus('dirty'); };
  const speech = (patch: Partial<CharacterDraft['speech']>) => change({ speech: { ...draft.speech, ...patch } });
  const appearance = (patch: Partial<CharacterDraft['appearance']>) => change({ appearance: { ...draft.appearance, ...patch } });
  async function save(quiet = false) {
    if (!draft.displayName.trim()) { if (!quiet) setError('请先填写角色名称。'); return null; }
    setStatus('saving'); setError('');
    try {
      if (!currentId.current) { const created = await api<CharacterProfile>('characters', { method: 'POST', body: JSON.stringify({ displayName: draft.displayName, draft, tags }) }); currentId.current = created.id; router.replace(`/apps/characters/${created.id}`); await load(created.id); return created.id; }
      const updated = await api<CharacterProfile>(`characters/${currentId.current}`, { method: 'PUT', body: JSON.stringify({ draft, tags }) }); setDetail((current) => current ? { ...current, ...updated } : current); setStatus('saved'); setTimeout(() => setStatus('clean'), 1200); return updated.id;
    } catch (cause) { setStatus('error'); setError(cause instanceof Error ? cause.message : String(cause)); return null; }
  }
  async function generate() {
    const id = currentId.current ?? await save(); if (!id || description.trim().length < 2) { setError('请填写用于生成的角色名称或描述。'); return; }
    setGenerating(true); setError(''); setNotice(''); try { const result = await api<{ draft: CharacterDraft; sources: CharacterSource[] }>(`characters/${id}/generate`, { method: 'POST', body: JSON.stringify({ description, useWeb: true }) }); setDraft(result.draft); await load(id); setNotice(`已生成可编辑草稿，并保存 ${result.sources.length} 条资料来源。`); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setGenerating(false); }
  }
  async function publish() { const id = currentId.current ?? await save(); if (!id) return; try { const version = await api<CharacterVersion>(`characters/${id}/publish`, { method: 'POST' }); await load(id); setNotice(`已发布 v${version.version}，使用此角色的应用现在可以发现更新。`); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function uploadAvatar(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !currentId.current) return; const dataUrl = await new Promise<string>((resolveValue, reject) => { const reader = new FileReader(); reader.onload = () => resolveValue(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); try { await api(`characters/${currentId.current}/assets`, { method: 'POST', body: JSON.stringify({ dataUrl, filename: file.name, kind: 'avatar' }) }); await load(currentId.current); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function importCard(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { const card = JSON.parse(await file.text()) as Record<string, unknown>; const created = await api<CharacterProfile>('characters/import-tavern', { method: 'POST', body: JSON.stringify({ card }) }); router.push(`/apps/characters/${created.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : '角色卡 JSON 无效'); } }
  async function exportCard() { if (!currentId.current) return; try { const card = await api<Record<string, unknown>>(`characters/${currentId.current}/export-tavern`); const url = URL.createObjectURL(new Blob([JSON.stringify(card, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `${detail?.slug ?? 'character'}.json`; a.click(); URL.revokeObjectURL(url); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function addRelationship() { if (!currentId.current || !relationTarget) return; try { await api(`characters/${currentId.current}/relationship`, { method: 'PUT', body: JSON.stringify({ toCharacterId: relationTarget, relationType, description: relationDescription }) }); setRelationTarget(''); setRelationType(''); setRelationDescription(''); await load(currentId.current); setNotice('角色关系已保存。'); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function removeRelationship(id: string) { if (!currentId.current) return; try { await api(`characters/${currentId.current}/relationships/${id}`, { method: 'DELETE' }); await load(currentId.current); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  const previewPrompt = useMemo(() => { const identity = [draft.identity, draft.background].filter(Boolean).join(' '); return `${draft.displayName || '未命名角色'}\n${identity}\n${draft.personality.join('；')}\n${draft.appearance.description}`.trim(); }, [draft]);
  return <main className="character-editor-shell">
    <header className="character-editor-toolbar"><Link href="/apps/characters">← 角色资料库</Link><span>{status === 'saving' ? '保存中…' : status === 'dirty' ? '等待自动保存' : status === 'saved' ? '已保存' : detail?.latestVersion ? `已发布 v${detail.latestVersion}` : '未发布草稿'}</span><div><button onClick={() => importInput.current?.click()}>导入 JSON</button><button onClick={() => void exportCard()} disabled={!currentId.current}>导出</button><button className="publish-character" onClick={() => void publish()}>发布版本</button></div></header>
    <div className="character-editor-layout">
      <aside className="character-editor-nav"><div className="character-profile-mini" onClick={() => currentId.current && avatarInput.current?.click()}>{detail?.avatarUrl ? <Image src={detail.avatarUrl} fill unoptimized sizes="84px" alt=""/> : <span>{draft.displayName.slice(0,1) || '角'}</span>}<small>{currentId.current ? '点击更换头像' : '保存后设置头像'}</small></div><h1>{draft.displayName || '新角色'}</h1><p>{draft.work || draft.world || '尚未设置作品或世界'}</p>{([['identity','身份与经历'],['personality','性格与表达'],['appearance','外观与素材'],['relations','关系与来源'],['publish','应用与版本']] as [Section,string][]).map(([id,label]) => <button className={section===id?'active':''} onClick={() => setSection(id)} key={id}>{label}</button>)}</aside>
      <article className="character-editor-main">
        {error && <p className="editor-error">{error}</p>}{notice && <p className="character-notice">{notice}</p>}
        <section className="character-ai-draft"><div><strong>从名字或资料开始</strong><p>系统会联网查找资料并生成结构化草稿，不会自动发布。</p></div><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="例如：芙宁娜（原神），重点保留她表面夸张、内心敏感的反差"/><button onClick={() => void generate()} disabled={generating}>{generating ? '正在检索与整理…' : '生成可编辑草稿'}</button></section>
        {section === 'identity' && <EditorSection title="身份与经历" intro="先写清楚她是谁，再写她为什么会成为现在的样子。"><div className="character-form-grid"><Field label="角色名称"><input value={draft.displayName} onChange={(event) => change({displayName:event.target.value})}/></Field><Field label="英文名 / 拼音"><input value={draft.englishName} onChange={(event) => change({englishName:event.target.value})}/></Field><Field label="来源"><select value={draft.originType} onChange={(event) => change({originType:event.target.value as 'original'|'ip'})}><option value="original">原创角色</option><option value="ip">已有作品角色</option></select></Field><Field label="所属作品"><input value={draft.work} onChange={(event) => change({work:event.target.value})}/></Field><Field label="所属世界"><input value={draft.world} onChange={(event) => change({world:event.target.value})}/></Field><Field label="别名"><input value={draft.aliases.join('，')} onChange={(event) => change({aliases:event.target.value.split(/[，,]/).map(v=>v.trim()).filter(Boolean)})}/></Field></div><Field label="一句话摘要"><textarea rows={2} value={draft.summary} onChange={(event) => change({summary:event.target.value})}/></Field><Field label="身份"><textarea rows={5} value={draft.identity} onChange={(event) => change({identity:event.target.value})}/></Field><Field label="关键经历"><textarea rows={7} value={draft.background} onChange={(event) => change({background:event.target.value})}/></Field><Field label="当前处境"><textarea rows={4} value={draft.currentSituation} onChange={(event) => change({currentSituation:event.target.value})}/></Field><Field label="标签"><input value={tags.join('，')} onChange={(event) => {setTags(event.target.value.split(/[，,]/).map(v=>v.trim()).filter(Boolean));setStatus('dirty');}}/></Field></EditorSection>}
        {section === 'personality' && <EditorSection title="性格与表达" intro="每行一条，让性格、驱动力和语言习惯可以被其他应用分别使用。"><ListField label="性格特点" value={draft.personality} onChange={(value)=>change({personality:value})}/><div className="character-form-grid"><ListField label="核心动机" value={draft.motivations} onChange={(value)=>change({motivations:value})}/><ListField label="信念" value={draft.beliefs} onChange={(value)=>change({beliefs:value})}/><ListField label="秘密" value={draft.secrets} onChange={(value)=>change({secrets:value})}/><ListField label="边界与禁忌" value={draft.boundaries} onChange={(value)=>change({boundaries:value})}/></div><Field label="说话语气"><textarea rows={4} value={draft.speech.tone} onChange={(event)=>speech({tone:event.target.value})}/></Field><Field label="表达习惯与反差"><textarea rows={4} value={draft.speech.habits} onChange={(event)=>speech({habits:event.target.value})}/></Field><div className="character-form-grid"><ListField label="口头禅" value={draft.speech.catchphrases} onChange={(value)=>speech({catchphrases:value})}/><ListField label="示例对白" value={draft.speech.examples} onChange={(value)=>speech({examples:value})}/><ListField label="喜欢" value={draft.likes} onChange={(value)=>change({likes:value})}/><ListField label="不喜欢" value={draft.dislikes} onChange={(value)=>change({dislikes:value})}/><ListField label="恐惧" value={draft.fears} onChange={(value)=>change({fears:value})}/></div></EditorSection>}
        {section === 'appearance' && <EditorSection title="外观与素材" intro="稳定外观锚点会被邻舍用于对话与图像生成；情境服装仍由应用决定。"><button className="avatar-upload-button" disabled={!currentId.current} onClick={()=>avatarInput.current?.click()}>上传角色头像</button><Field label="整体外观描述"><textarea rows={7} value={draft.appearance.description} onChange={(event)=>appearance({description:event.target.value})}/></Field><div className="character-form-grid"><Field label="发型与发色"><textarea rows={3} value={draft.appearance.hair} onChange={(event)=>appearance({hair:event.target.value})}/></Field><Field label="眼睛"><textarea rows={3} value={draft.appearance.eyes} onChange={(event)=>appearance({eyes:event.target.value})}/></Field><Field label="体态"><textarea rows={3} value={draft.appearance.build} onChange={(event)=>appearance({build:event.target.value})}/></Field><ListField label="常用服装" value={draft.appearance.outfits} onChange={(value)=>appearance({outfits:value})}/><ListField label="标志性饰品" value={draft.appearance.accessories} onChange={(value)=>appearance({accessories:value})}/></div><Field label="额外运行规则"><textarea rows={5} value={draft.extraRules} onChange={(event)=>change({extraRules:event.target.value})}/></Field></EditorSection>}
        {section === 'relations' && <EditorSection title="关系与资料来源" intro="关系是有方向的；“A 如何看待 B”与“B 如何看待 A”可以不同。"><div className="character-relation-form"><Field label="关联角色"><select value={relationTarget} onChange={(event)=>setRelationTarget(event.target.value)}><option value="">选择资料库中的角色</option>{library.filter(item=>item.id!==currentId.current).map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></Field><Field label="关系类型"><input value={relationType} onChange={(event)=>setRelationType(event.target.value)} placeholder="朋友、宿敌、家人…"/></Field><Field label="关系说明"><textarea rows={3} value={relationDescription} onChange={(event)=>setRelationDescription(event.target.value)} placeholder="这个角色如何看待对方？"/></Field><button disabled={!currentId.current||!relationTarget} onClick={()=>void addRelationship()}>保存关系</button></div><div className="character-relation-list">{detail?.relationships.map(rel=>{const otherId=rel.fromCharacterId===detail.id?rel.toCharacterId:rel.fromCharacterId;const other=library.find(item=>item.id===otherId);return <div key={rel.id}><strong>{rel.relationType||'关系'} · {other?.displayName||'未知角色'}</strong><span>{rel.fromCharacterId===detail.id?'由当前角色指向对方':'由对方指向当前角色'}</span><p>{rel.description||'未填写说明'}</p><button onClick={()=>void removeRelationship(rel.id)}>移除</button></div>})}{!detail?.relationships.length&&<p>尚未建立角色关系。</p>}</div><h3>资料来源</h3><div className="character-source-list">{detail?.sources.map(source=><a href={source.url??undefined} target="_blank" rel="noreferrer" key={source.id}><strong>{source.title}</strong><span>{source.sourceType} · {new Date(source.fetchedAt).toLocaleDateString()}</span><p>{source.excerpt.slice(0,220)}</p></a>)}{!detail?.sources.length&&<p>还没有资料来源。使用上方智能草稿或导入角色卡后会在这里记录。</p>}</div></EditorSection>}
        {section === 'publish' && <EditorSection title="应用与版本" intro="草稿实时供创作工具查看；只有发布版本才会交给邻舍等运行应用。"><div className="character-version-summary"><strong>{detail?.latestVersion ? `当前发布版本 v${detail.latestVersion}` : '尚未发布'}</strong><button onClick={()=>void publish()}>发布当前草稿</button></div><h3>邻舍人格预览</h3><pre className="character-prompt-preview">{previewPrompt || '填写角色资料后，这里会显示适配邻舍的内容摘要。'}</pre><h3>版本记录</h3><div className="character-version-list">{detail?.versions.map(version=><div key={version.version}><strong>v{version.version}</strong><span>{new Date(version.createdAt).toLocaleString()}</span></div>)}</div><h3>使用此角色的应用</h3><div className="character-version-list">{detail?.links.map(link=><div key={`${link.app_id}-${link.local_id}`}><strong>{link.app_id}</strong><span>使用 v{link.source_version}{link.local_modified?' · 存在本地修改':''}</span></div>)}{!detail?.links.length&&<p>还没有应用导入这个角色。</p>}</div></EditorSection>}
        <button className="character-manual-save" onClick={()=>void save()}>保存草稿</button>
      </article>
      <aside className="character-live-card"><div className="character-live-portrait">{detail?.avatarUrl?<Image src={detail.avatarUrl} fill unoptimized sizes="240px" alt=""/>:<span>{draft.displayName.slice(0,1)||'角'}</span>}</div><p>{draft.work||draft.world||'原创世界'}</p><h2>{draft.displayName||'未命名角色'}</h2><span>{draft.summary||draft.identity||'角色摘要会显示在这里。'}</span><div>{draft.personality.slice(0,4).map(item=><b key={item}>{item.slice(0,16)}</b>)}</div></aside>
    </div>
    <input ref={avatarInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event)=>void uploadAvatar(event)}/><input ref={importInput} hidden type="file" accept="application/json,.json" onChange={(event)=>void importCard(event)}/>
  </main>;
}

function EditorSection({title,intro,children}:{title:string;intro:string;children:React.ReactNode}) { return <section className="character-editor-section"><header><p className="eyebrow">CHARACTER DOSSIER</p><h2>{title}</h2><span>{intro}</span></header>{children}</section>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="character-field"><span>{label}</span>{children}</label>; }
function ListField({label,value,onChange}:{label:string;value:string[];onChange:(value:string[])=>void}) { return <Field label={`${label}（每行一条）`}><textarea rows={Math.max(4,value.length+1)} value={joined(value)} onChange={(event)=>onChange(lines(event.target.value))}/></Field>; }
