// GENERATED by scripts/build-world-data.mjs from Natural Earth 1:50m (public domain). Do not edit by hand.

/** One country or dependent territory, as <WorldMap> and the country search use it. */
export interface Country {
  /** ISO 3166-1 alpha-2, e.g. "JP". This is the id <WorldMap> works in. */
  code: string
  /** ISO 3166-1 alpha-3, e.g. "JPN". */
  code3: string
  /** English name, e.g. "Japan". People read `countryName(country)`, in the app's language. */
  name: string
  /** UN region, e.g. "Asia". */
  region: string
  /** UN subregion, e.g. "Eastern Asia". */
  subregion: string
  /** A point inside the country, good for centring a map on it. */
  lat: number
  lon: number
}

/** Every country <WorldMap> can draw, sorted by name. */
export const COUNTRIES: readonly Country[] = [
  {"code":"AF","code3":"AFG","name":"Afghanistan","region":"Asia","subregion":"Southern Asia","lat":34.16,"lon":66.5},
  {"code":"AX","code3":"ALA","name":"Åland","region":"Europe","subregion":"Northern Europe","lat":60.16,"lon":19.87},
  {"code":"AL","code3":"ALB","name":"Albania","region":"Europe","subregion":"Southern Europe","lat":40.65,"lon":20.11},
  {"code":"DZ","code3":"DZA","name":"Algeria","region":"Africa","subregion":"Northern Africa","lat":27.4,"lon":2.81},
  {"code":"AS","code3":"ASM","name":"American Samoa","region":"Oceania","subregion":"Polynesia","lat":-14.33,"lon":-170.75},
  {"code":"AD","code3":"AND","name":"Andorra","region":"Europe","subregion":"Southern Europe","lat":42.55,"lon":1.54},
  {"code":"AO","code3":"AGO","name":"Angola","region":"Africa","subregion":"Middle Africa","lat":-12.18,"lon":17.98},
  {"code":"AI","code3":"AIA","name":"Anguilla","region":"Americas","subregion":"Caribbean","lat":18.24,"lon":-63.03},
  {"code":"AQ","code3":"ATA","name":"Antarctica","region":"Antarctica","subregion":"Antarctica","lat":-79.84,"lon":35.89},
  {"code":"AG","code3":"ATG","name":"Antigua and Barbuda","region":"Americas","subregion":"Caribbean","lat":17.35,"lon":-61.79},
  {"code":"AR","code3":"ARG","name":"Argentina","region":"Americas","subregion":"South America","lat":-33.5,"lon":-64.17},
  {"code":"AM","code3":"ARM","name":"Armenia","region":"Asia","subregion":"Western Asia","lat":40.46,"lon":44.8},
  {"code":"AW","code3":"ABW","name":"Aruba","region":"Americas","subregion":"Caribbean","lat":12.52,"lon":-69.97},
  {"code":"AU","code3":"AUS","name":"Australia","region":"Oceania","subregion":"Australia and New Zealand","lat":-24.13,"lon":134.05},
  {"code":"AT","code3":"AUT","name":"Austria","region":"Europe","subregion":"Western Europe","lat":47.52,"lon":14.13},
  {"code":"AZ","code3":"AZE","name":"Azerbaijan","region":"Asia","subregion":"Western Asia","lat":40.4,"lon":47.21},
  {"code":"BH","code3":"BHR","name":"Bahrain","region":"Asia","subregion":"Western Asia","lat":26.06,"lon":50.55},
  {"code":"BD","code3":"BGD","name":"Bangladesh","region":"Asia","subregion":"Southern Asia","lat":24.21,"lon":89.68},
  {"code":"BB","code3":"BRB","name":"Barbados","region":"Americas","subregion":"Caribbean","lat":13.16,"lon":-59.57},
  {"code":"BY","code3":"BLR","name":"Belarus","region":"Europe","subregion":"Eastern Europe","lat":53.82,"lon":28.42},
  {"code":"BE","code3":"BEL","name":"Belgium","region":"Europe","subregion":"Western Europe","lat":50.79,"lon":4.8},
  {"code":"BZ","code3":"BLZ","name":"Belize","region":"Americas","subregion":"Central America","lat":17.2,"lon":-88.71},
  {"code":"BJ","code3":"BEN","name":"Benin","region":"Africa","subregion":"Western Africa","lat":10.32,"lon":2.35},
  {"code":"BM","code3":"BMU","name":"Bermuda","region":"Americas","subregion":"Northern America","lat":32.3,"lon":-64.76},
  {"code":"BT","code3":"BTN","name":"Bhutan","region":"Asia","subregion":"Southern Asia","lat":27.54,"lon":90.04},
  {"code":"BO","code3":"BOL","name":"Bolivia","region":"Americas","subregion":"South America","lat":-16.67,"lon":-64.59},
  {"code":"BA","code3":"BIH","name":"Bosnia and Herzegovina","region":"Europe","subregion":"Southern Europe","lat":44.09,"lon":18.07},
  {"code":"BW","code3":"BWA","name":"Botswana","region":"Africa","subregion":"Southern Africa","lat":-22.1,"lon":24.18},
  {"code":"BR","code3":"BRA","name":"Brazil","region":"Americas","subregion":"South America","lat":-12.1,"lon":-49.56},
  {"code":"IO","code3":"IOT","name":"British Indian Ocean Territory","region":"Africa","subregion":"Seven seas (open ocean)","lat":-6.19,"lon":71.35},
  {"code":"VG","code3":"VGB","name":"British Virgin Islands","region":"Americas","subregion":"Caribbean","lat":18.43,"lon":-64.64},
  {"code":"BN","code3":"BRN","name":"Brunei","region":"Asia","subregion":"South-Eastern Asia","lat":4.45,"lon":114.55},
  {"code":"BG","code3":"BGR","name":"Bulgaria","region":"Europe","subregion":"Eastern Europe","lat":42.51,"lon":25.16},
  {"code":"BF","code3":"BFA","name":"Burkina Faso","region":"Africa","subregion":"Western Africa","lat":12.67,"lon":-1.36},
  {"code":"BI","code3":"BDI","name":"Burundi","region":"Africa","subregion":"Eastern Africa","lat":-3.33,"lon":29.92},
  {"code":"KH","code3":"KHM","name":"Cambodia","region":"Asia","subregion":"South-Eastern Asia","lat":12.65,"lon":104.5},
  {"code":"CM","code3":"CMR","name":"Cameroon","region":"Africa","subregion":"Middle Africa","lat":4.59,"lon":12.47},
  {"code":"CA","code3":"CAN","name":"Canada","region":"Americas","subregion":"Northern America","lat":60.32,"lon":-101.91},
  {"code":"CV","code3":"CPV","name":"Cape Verde","region":"Africa","subregion":"Western Africa","lat":15.07,"lon":-23.64},
  {"code":"KY","code3":"CYM","name":"Cayman Islands","region":"Americas","subregion":"Caribbean","lat":19.32,"lon":-81.24},
  {"code":"CF","code3":"CAF","name":"Central African Republic","region":"Africa","subregion":"Middle Africa","lat":6.99,"lon":20.91},
  {"code":"TD","code3":"TCD","name":"Chad","region":"Africa","subregion":"Middle Africa","lat":15.14,"lon":18.65},
  {"code":"CL","code3":"CHL","name":"Chile","region":"Americas","subregion":"South America","lat":-38.15,"lon":-72.32},
  {"code":"CO","code3":"COL","name":"Colombia","region":"Americas","subregion":"South America","lat":3.37,"lon":-73.17},
  {"code":"KM","code3":"COM","name":"Comoros","region":"Africa","subregion":"Eastern Africa","lat":-11.73,"lon":43.32},
  {"code":"CK","code3":"COK","name":"Cook Islands","region":"Oceania","subregion":"Polynesia","lat":-21.22,"lon":-159.79},
  {"code":"CR","code3":"CRI","name":"Costa Rica","region":"Americas","subregion":"Central America","lat":10.07,"lon":-84.08},
  {"code":"HR","code3":"HRV","name":"Croatia","region":"Europe","subregion":"Southern Europe","lat":45.81,"lon":16.37},
  {"code":"CU","code3":"CUB","name":"Cuba","region":"Americas","subregion":"Caribbean","lat":21.33,"lon":-77.98},
  {"code":"CW","code3":"CUW","name":"Curaçao","region":"Americas","subregion":"Caribbean","lat":12.15,"lon":-68.92},
  {"code":"CY","code3":"CYP","name":"Cyprus","region":"Asia","subregion":"Western Asia","lat":34.91,"lon":33.08},
  {"code":"CZ","code3":"CZE","name":"Czech Republic","region":"Europe","subregion":"Eastern Europe","lat":49.88,"lon":15.38},
  {"code":"CD","code3":"COD","name":"Democratic Republic of the Congo","region":"Africa","subregion":"Middle Africa","lat":-1.86,"lon":23.46},
  {"code":"DK","code3":"DNK","name":"Denmark","region":"Europe","subregion":"Northern Europe","lat":55.97,"lon":9.02},
  {"code":"DJ","code3":"DJI","name":"Djibouti","region":"Africa","subregion":"Eastern Africa","lat":11.98,"lon":42.5},
  {"code":"DM","code3":"DMA","name":"Dominica","region":"Americas","subregion":"Caribbean","lat":15.46,"lon":-61.34},
  {"code":"DO","code3":"DOM","name":"Dominican Republic","region":"Americas","subregion":"Caribbean","lat":19.1,"lon":-70.65},
  {"code":"TL","code3":"TLS","name":"East Timor","region":"Asia","subregion":"South-Eastern Asia","lat":-8.8,"lon":125.85},
  {"code":"EC","code3":"ECU","name":"Ecuador","region":"Americas","subregion":"South America","lat":-1.26,"lon":-78.19},
  {"code":"EG","code3":"EGY","name":"Egypt","region":"Africa","subregion":"Northern Africa","lat":26.19,"lon":29.45},
  {"code":"SV","code3":"SLV","name":"El Salvador","region":"Americas","subregion":"Central America","lat":13.69,"lon":-88.89},
  {"code":"GQ","code3":"GNQ","name":"Equatorial Guinea","region":"Africa","subregion":"Middle Africa","lat":2.33,"lon":8.99},
  {"code":"ER","code3":"ERI","name":"Eritrea","region":"Africa","subregion":"Eastern Africa","lat":15.79,"lon":38.29},
  {"code":"EE","code3":"EST","name":"Estonia","region":"Europe","subregion":"Northern Europe","lat":58.72,"lon":25.87},
  {"code":"SZ","code3":"SWZ","name":"Eswatini","region":"Africa","subregion":"Southern Africa","lat":-26.53,"lon":31.47},
  {"code":"ET","code3":"ETH","name":"Ethiopia","region":"Africa","subregion":"Eastern Africa","lat":8.03,"lon":39.09},
  {"code":"FK","code3":"FLK","name":"Falkland Islands","region":"Americas","subregion":"South America","lat":-51.61,"lon":-58.74},
  {"code":"FO","code3":"FRO","name":"Faroe Islands","region":"Europe","subregion":"Northern Europe","lat":62.19,"lon":-7.06},
  {"code":"FM","code3":"FSM","name":"Federated States of Micronesia","region":"Oceania","subregion":"Micronesia","lat":6.89,"lon":158.23},
  {"code":"FJ","code3":"FJI","name":"Fiji","region":"Oceania","subregion":"Melanesia","lat":-17.83,"lon":177.98},
  {"code":"FI","code3":"FIN","name":"Finland","region":"Europe","subregion":"Northern Europe","lat":63.25,"lon":27.28},
  {"code":"FR","code3":"FRA","name":"France","region":"Europe","subregion":"Western Europe","lat":46.7,"lon":2.55},
  {"code":"PF","code3":"PYF","name":"French Polynesia","region":"Oceania","subregion":"Polynesia","lat":-17.63,"lon":-149.46},
  {"code":"TF","code3":"ATF","name":"French Southern and Antarctic Lands","region":"Africa","subregion":"Seven seas (open ocean)","lat":-49.3,"lon":69.12},
  {"code":"GA","code3":"GAB","name":"Gabon","region":"Africa","subregion":"Middle Africa","lat":-0.44,"lon":11.84},
  {"code":"GE","code3":"GEO","name":"Georgia","region":"Asia","subregion":"Western Asia","lat":41.87,"lon":43.74},
  {"code":"DE","code3":"DEU","name":"Germany","region":"Europe","subregion":"Western Europe","lat":50.96,"lon":9.68},
  {"code":"GH","code3":"GHA","name":"Ghana","region":"Africa","subregion":"Western Africa","lat":7.72,"lon":-1.04},
  {"code":"GR","code3":"GRC","name":"Greece","region":"Europe","subregion":"Southern Europe","lat":39.49,"lon":21.73},
  {"code":"GL","code3":"GRL","name":"Greenland","region":"Americas","subregion":"Northern America","lat":74.32,"lon":-39.34},
  {"code":"GD","code3":"GRD","name":"Grenada","region":"Americas","subregion":"Caribbean","lat":12.11,"lon":-61.68},
  {"code":"GU","code3":"GUM","name":"Guam","region":"Oceania","subregion":"Micronesia","lat":13.35,"lon":144.7},
  {"code":"GT","code3":"GTM","name":"Guatemala","region":"Americas","subregion":"Central America","lat":14.98,"lon":-90.5},
  {"code":"GG","code3":"GGY","name":"Guernsey","region":"Europe","subregion":"Northern Europe","lat":49.46,"lon":-2.56},
  {"code":"GN","code3":"GIN","name":"Guinea","region":"Africa","subregion":"Western Africa","lat":10.62,"lon":-10.02},
  {"code":"GW","code3":"GNB","name":"Guinea-Bissau","region":"Africa","subregion":"Western Africa","lat":12.16,"lon":-14.52},
  {"code":"GY","code3":"GUY","name":"Guyana","region":"Americas","subregion":"South America","lat":5.12,"lon":-58.94},
  {"code":"HT","code3":"HTI","name":"Haiti","region":"Americas","subregion":"Caribbean","lat":19.26,"lon":-72.22},
  {"code":"HM","code3":"HMD","name":"Heard Island and McDonald Islands","region":"Africa","subregion":"Seven seas (open ocean)","lat":-53.1,"lon":73.51},
  {"code":"HN","code3":"HND","name":"Honduras","region":"Americas","subregion":"Central America","lat":14.79,"lon":-86.89},
  {"code":"HK","code3":"HKG","name":"Hong Kong","region":"Asia","subregion":"Eastern Asia","lat":22.45,"lon":114.1},
  {"code":"HU","code3":"HUN","name":"Hungary","region":"Europe","subregion":"Eastern Europe","lat":47.09,"lon":19.45},
  {"code":"IS","code3":"ISL","name":"Iceland","region":"Europe","subregion":"Northern Europe","lat":64.78,"lon":-18.67},
  {"code":"IN","code3":"IND","name":"India","region":"Asia","subregion":"Southern Asia","lat":22.69,"lon":79.36},
  {"code":"ID","code3":"IDN","name":"Indonesia","region":"Asia","subregion":"South-Eastern Asia","lat":-0.95,"lon":101.89},
  {"code":"IR","code3":"IRN","name":"Iran","region":"Asia","subregion":"Southern Asia","lat":32.17,"lon":54.93},
  {"code":"IQ","code3":"IRQ","name":"Iraq","region":"Asia","subregion":"Western Asia","lat":33.09,"lon":43.26},
  {"code":"IE","code3":"IRL","name":"Ireland","region":"Europe","subregion":"Northern Europe","lat":53.08,"lon":-7.8},
  {"code":"IM","code3":"IMN","name":"Isle of Man","region":"Europe","subregion":"Northern Europe","lat":54.22,"lon":-4.53},
  {"code":"IL","code3":"ISR","name":"Israel","region":"Asia","subregion":"Western Asia","lat":30.91,"lon":34.85},
  {"code":"IT","code3":"ITA","name":"Italy","region":"Europe","subregion":"Southern Europe","lat":44.73,"lon":11.08},
  {"code":"CI","code3":"CIV","name":"Ivory Coast","region":"Africa","subregion":"Western Africa","lat":7.49,"lon":-5.57},
  {"code":"JM","code3":"JAM","name":"Jamaica","region":"Americas","subregion":"Caribbean","lat":18.14,"lon":-77.32},
  {"code":"JP","code3":"JPN","name":"Japan","region":"Asia","subregion":"Eastern Asia","lat":36.14,"lon":138.44},
  {"code":"JE","code3":"JEY","name":"Jersey","region":"Europe","subregion":"Northern Europe","lat":49.22,"lon":-2.09},
  {"code":"JO","code3":"JOR","name":"Jordan","region":"Asia","subregion":"Western Asia","lat":30.81,"lon":36.38},
  {"code":"KZ","code3":"KAZ","name":"Kazakhstan","region":"Asia","subregion":"Central Asia","lat":49.05,"lon":68.69},
  {"code":"KE","code3":"KEN","name":"Kenya","region":"Africa","subregion":"Eastern Africa","lat":0.55,"lon":37.91},
  {"code":"KI","code3":"KIR","name":"Kiribati","region":"Oceania","subregion":"Micronesia","lat":1.82,"lon":-157.38},
  {"code":"KW","code3":"KWT","name":"Kuwait","region":"Asia","subregion":"Western Asia","lat":29.41,"lon":47.31},
  {"code":"KG","code3":"KGZ","name":"Kyrgyzstan","region":"Asia","subregion":"Central Asia","lat":41.67,"lon":74.53},
  {"code":"LA","code3":"LAO","name":"Laos","region":"Asia","subregion":"South-Eastern Asia","lat":19.43,"lon":102.53},
  {"code":"LV","code3":"LVA","name":"Latvia","region":"Europe","subregion":"Northern Europe","lat":57.07,"lon":25.46},
  {"code":"LB","code3":"LBN","name":"Lebanon","region":"Asia","subregion":"Western Asia","lat":34.13,"lon":35.99},
  {"code":"LS","code3":"LSO","name":"Lesotho","region":"Africa","subregion":"Southern Africa","lat":-29.48,"lon":28.25},
  {"code":"LR","code3":"LBR","name":"Liberia","region":"Africa","subregion":"Western Africa","lat":6.45,"lon":-9.46},
  {"code":"LY","code3":"LBY","name":"Libya","region":"Africa","subregion":"Northern Africa","lat":26.64,"lon":18.01},
  {"code":"LI","code3":"LIE","name":"Liechtenstein","region":"Europe","subregion":"Western Europe","lat":47.11,"lon":9.56},
  {"code":"LT","code3":"LTU","name":"Lithuania","region":"Europe","subregion":"Northern Europe","lat":55.1,"lon":24.09},
  {"code":"LU","code3":"LUX","name":"Luxembourg","region":"Europe","subregion":"Western Europe","lat":49.73,"lon":6.08},
  {"code":"MO","code3":"MAC","name":"Macau","region":"Asia","subregion":"Eastern Asia","lat":22.13,"lon":113.56},
  {"code":"MG","code3":"MDG","name":"Madagascar","region":"Africa","subregion":"Eastern Africa","lat":-18.63,"lon":46.7},
  {"code":"MW","code3":"MWI","name":"Malawi","region":"Africa","subregion":"Eastern Africa","lat":-13.39,"lon":33.61},
  {"code":"MY","code3":"MYS","name":"Malaysia","region":"Asia","subregion":"South-Eastern Asia","lat":2.53,"lon":113.84},
  {"code":"MV","code3":"MDV","name":"Maldives","region":"Asia","subregion":"Southern Asia","lat":4.17,"lon":73.51},
  {"code":"ML","code3":"MLI","name":"Mali","region":"Africa","subregion":"Western Africa","lat":18.69,"lon":-2.04},
  {"code":"MT","code3":"MLT","name":"Malta","region":"Europe","subregion":"Southern Europe","lat":35.89,"lon":14.43},
  {"code":"MH","code3":"MHL","name":"Marshall Islands","region":"Oceania","subregion":"Micronesia","lat":7.08,"lon":171.19},
  {"code":"MR","code3":"MRT","name":"Mauritania","region":"Africa","subregion":"Western Africa","lat":19.59,"lon":-9.74},
  {"code":"MU","code3":"MUS","name":"Mauritius","region":"Africa","subregion":"Eastern Africa","lat":-20.3,"lon":57.57},
  {"code":"MX","code3":"MEX","name":"Mexico","region":"Americas","subregion":"Central America","lat":23.92,"lon":-102.29},
  {"code":"MD","code3":"MDA","name":"Moldova","region":"Europe","subregion":"Eastern Europe","lat":47.43,"lon":28.49},
  {"code":"MC","code3":"MCO","name":"Monaco","region":"Europe","subregion":"Western Europe","lat":43.74,"lon":7.4},
  {"code":"MN","code3":"MNG","name":"Mongolia","region":"Asia","subregion":"Eastern Asia","lat":46,"lon":104.15},
  {"code":"ME","code3":"MNE","name":"Montenegro","region":"Europe","subregion":"Southern Europe","lat":42.8,"lon":19.14},
  {"code":"MS","code3":"MSR","name":"Montserrat","region":"Americas","subregion":"Caribbean","lat":16.74,"lon":-62.19},
  {"code":"MA","code3":"MAR","name":"Morocco","region":"Africa","subregion":"Northern Africa","lat":31.65,"lon":-7.19},
  {"code":"MZ","code3":"MOZ","name":"Mozambique","region":"Africa","subregion":"Eastern Africa","lat":-13.94,"lon":37.84},
  {"code":"MM","code3":"MMR","name":"Myanmar","region":"Asia","subregion":"South-Eastern Asia","lat":21.57,"lon":95.8},
  {"code":"NA","code3":"NAM","name":"Namibia","region":"Africa","subregion":"Southern Africa","lat":-20.58,"lon":17.11},
  {"code":"NR","code3":"NRU","name":"Nauru","region":"Oceania","subregion":"Micronesia","lat":-0.52,"lon":166.93},
  {"code":"NP","code3":"NPL","name":"Nepal","region":"Asia","subregion":"Southern Asia","lat":28.3,"lon":83.64},
  {"code":"NL","code3":"NLD","name":"Netherlands","region":"Europe","subregion":"Western Europe","lat":52.42,"lon":5.61},
  {"code":"NC","code3":"NCL","name":"New Caledonia","region":"Oceania","subregion":"Melanesia","lat":-21.06,"lon":165.08},
  {"code":"NZ","code3":"NZL","name":"New Zealand","region":"Oceania","subregion":"Australia and New Zealand","lat":-39.76,"lon":172.79},
  {"code":"NI","code3":"NIC","name":"Nicaragua","region":"Americas","subregion":"Central America","lat":12.67,"lon":-85.07},
  {"code":"NE","code3":"NER","name":"Niger","region":"Africa","subregion":"Western Africa","lat":17.45,"lon":9.5},
  {"code":"NG","code3":"NGA","name":"Nigeria","region":"Africa","subregion":"Western Africa","lat":9.44,"lon":7.5},
  {"code":"NU","code3":"NIU","name":"Niue","region":"Oceania","subregion":"Polynesia","lat":-19.05,"lon":-169.86},
  {"code":"NF","code3":"NFK","name":"Norfolk Island","region":"Oceania","subregion":"Australia and New Zealand","lat":-29.03,"lon":167.95},
  {"code":"KP","code3":"PRK","name":"North Korea","region":"Asia","subregion":"Eastern Asia","lat":39.89,"lon":126.44},
  {"code":"MK","code3":"MKD","name":"North Macedonia","region":"Europe","subregion":"Southern Europe","lat":41.56,"lon":21.56},
  {"code":"MP","code3":"MNP","name":"Northern Mariana Islands","region":"Oceania","subregion":"Micronesia","lat":15.19,"lon":145.73},
  {"code":"NO","code3":"NOR","name":"Norway","region":"Europe","subregion":"Northern Europe","lat":61.36,"lon":9.68},
  {"code":"OM","code3":"OMN","name":"Oman","region":"Asia","subregion":"Western Asia","lat":22.12,"lon":57.34},
  {"code":"PK","code3":"PAK","name":"Pakistan","region":"Asia","subregion":"Southern Asia","lat":29.33,"lon":68.55},
  {"code":"PW","code3":"PLW","name":"Palau","region":"Oceania","subregion":"Micronesia","lat":7.52,"lon":134.58},
  {"code":"PS","code3":"PSE","name":"Palestine","region":"Asia","subregion":"Western Asia","lat":32.05,"lon":35.29},
  {"code":"PA","code3":"PAN","name":"Panama","region":"Americas","subregion":"Central America","lat":8.72,"lon":-80.35},
  {"code":"PG","code3":"PNG","name":"Papua New Guinea","region":"Oceania","subregion":"Melanesia","lat":-5.7,"lon":143.91},
  {"code":"PY","code3":"PRY","name":"Paraguay","region":"Americas","subregion":"South America","lat":-21.67,"lon":-60.15},
  {"code":"CN","code3":"CHN","name":"People's Republic of China","region":"Asia","subregion":"Eastern Asia","lat":32.5,"lon":106.34},
  {"code":"PE","code3":"PER","name":"Peru","region":"Americas","subregion":"South America","lat":-12.98,"lon":-72.9},
  {"code":"PH","code3":"PHL","name":"Philippines","region":"Asia","subregion":"South-Eastern Asia","lat":11.2,"lon":122.47},
  {"code":"PN","code3":"PCN","name":"Pitcairn Islands","region":"Oceania","subregion":"Polynesia","lat":-24.36,"lon":-128.32},
  {"code":"PL","code3":"POL","name":"Poland","region":"Europe","subregion":"Eastern Europe","lat":51.99,"lon":19.49},
  {"code":"PT","code3":"PRT","name":"Portugal","region":"Europe","subregion":"Southern Europe","lat":39.61,"lon":-8.27},
  {"code":"PR","code3":"PRI","name":"Puerto Rico","region":"Americas","subregion":"Caribbean","lat":18.23,"lon":-66.48},
  {"code":"QA","code3":"QAT","name":"Qatar","region":"Asia","subregion":"Western Asia","lat":25.24,"lon":51.14},
  {"code":"CG","code3":"COG","name":"Republic of the Congo","region":"Africa","subregion":"Middle Africa","lat":0.14,"lon":15.9},
  {"code":"RO","code3":"ROU","name":"Romania","region":"Europe","subregion":"Eastern Europe","lat":45.73,"lon":24.97},
  {"code":"RU","code3":"RUS","name":"Russia","region":"Europe","subregion":"Eastern Europe","lat":58.25,"lon":44.69},
  {"code":"RW","code3":"RWA","name":"Rwanda","region":"Africa","subregion":"Eastern Africa","lat":-1.9,"lon":30.1},
  {"code":"BL","code3":"BLM","name":"Saint Barthélemy","region":"Americas","subregion":"Caribbean","lat":17.9,"lon":-62.83},
  {"code":"SH","code3":"SHN","name":"Saint Helena","region":"Africa","subregion":"Western Africa","lat":-15.95,"lon":-5.71},
  {"code":"KN","code3":"KNA","name":"Saint Kitts and Nevis","region":"Americas","subregion":"Caribbean","lat":17.34,"lon":-62.76},
  {"code":"LC","code3":"LCA","name":"Saint Lucia","region":"Americas","subregion":"Caribbean","lat":13.89,"lon":-60.98},
  {"code":"MF","code3":"MAF","name":"Saint Martin","region":"Americas","subregion":"Caribbean","lat":18.08,"lon":-63.05},
  {"code":"PM","code3":"SPM","name":"Saint Pierre and Miquelon","region":"Americas","subregion":"Northern America","lat":47.04,"lon":-56.33},
  {"code":"VC","code3":"VCT","name":"Saint Vincent and the Grenadines","region":"Americas","subregion":"Caribbean","lat":13.09,"lon":-61.34},
  {"code":"WS","code3":"WSM","name":"Samoa","region":"Oceania","subregion":"Polynesia","lat":-13.64,"lon":-172.44},
  {"code":"SM","code3":"SMR","name":"San Marino","region":"Europe","subregion":"Southern Europe","lat":43.93,"lon":12.44},
  {"code":"ST","code3":"STP","name":"São Tomé and Príncipe","region":"Africa","subregion":"Middle Africa","lat":0.97,"lon":7.02},
  {"code":"SA","code3":"SAU","name":"Saudi Arabia","region":"Asia","subregion":"Western Asia","lat":23.81,"lon":44.7},
  {"code":"SN","code3":"SEN","name":"Senegal","region":"Africa","subregion":"Western Africa","lat":15.14,"lon":-14.78},
  {"code":"RS","code3":"SRB","name":"Serbia","region":"Europe","subregion":"Southern Europe","lat":44.19,"lon":20.79},
  {"code":"SC","code3":"SYC","name":"Seychelles","region":"Africa","subregion":"Eastern Africa","lat":-4.68,"lon":55.48},
  {"code":"SL","code3":"SLE","name":"Sierra Leone","region":"Africa","subregion":"Western Africa","lat":8.62,"lon":-11.76},
  {"code":"SG","code3":"SGP","name":"Singapore","region":"Asia","subregion":"South-Eastern Asia","lat":1.37,"lon":103.82},
  {"code":"SX","code3":"SXM","name":"Sint Maarten","region":"Americas","subregion":"Caribbean","lat":18.04,"lon":-63.07},
  {"code":"SK","code3":"SVK","name":"Slovakia","region":"Europe","subregion":"Eastern Europe","lat":48.73,"lon":19.05},
  {"code":"SI","code3":"SVN","name":"Slovenia","region":"Europe","subregion":"Southern Europe","lat":46.06,"lon":14.92},
  {"code":"SB","code3":"SLB","name":"Solomon Islands","region":"Oceania","subregion":"Melanesia","lat":-8.03,"lon":159.17},
  {"code":"SO","code3":"SOM","name":"Somalia","region":"Africa","subregion":"Eastern Africa","lat":3.57,"lon":45.19},
  {"code":"ZA","code3":"ZAF","name":"South Africa","region":"Africa","subregion":"Southern Africa","lat":-29.71,"lon":23.67},
  {"code":"GS","code3":"SGS","name":"South Georgia and the South Sandwich Islands","region":"Americas","subregion":"Seven seas (open ocean)","lat":-55.68,"lon":-31.06},
  {"code":"KR","code3":"KOR","name":"South Korea","region":"Asia","subregion":"Eastern Asia","lat":36.38,"lon":128.13},
  {"code":"SS","code3":"SSD","name":"South Sudan","region":"Africa","subregion":"Eastern Africa","lat":7.23,"lon":30.39},
  {"code":"ES","code3":"ESP","name":"Spain","region":"Europe","subregion":"Southern Europe","lat":40.09,"lon":-3.46},
  {"code":"LK","code3":"LKA","name":"Sri Lanka","region":"Asia","subregion":"Southern Asia","lat":7.58,"lon":80.7},
  {"code":"SD","code3":"SDN","name":"Sudan","region":"Africa","subregion":"Northern Africa","lat":16.33,"lon":29.26},
  {"code":"SR","code3":"SUR","name":"Suriname","region":"Americas","subregion":"South America","lat":4.14,"lon":-55.91},
  {"code":"SE","code3":"SWE","name":"Sweden","region":"Europe","subregion":"Northern Europe","lat":65.86,"lon":19.02},
  {"code":"CH","code3":"CHE","name":"Switzerland","region":"Europe","subregion":"Western Europe","lat":46.72,"lon":7.46},
  {"code":"SY","code3":"SYR","name":"Syria","region":"Asia","subregion":"Western Asia","lat":35.01,"lon":38.28},
  {"code":"TW","code3":"TWN","name":"Taiwan","region":"Asia","subregion":"Eastern Asia","lat":23.65,"lon":120.87},
  {"code":"TJ","code3":"TJK","name":"Tajikistan","region":"Asia","subregion":"Central Asia","lat":38.2,"lon":72.59},
  {"code":"TZ","code3":"TZA","name":"Tanzania","region":"Africa","subregion":"Eastern Africa","lat":-6.05,"lon":34.96},
  {"code":"TH","code3":"THA","name":"Thailand","region":"Asia","subregion":"South-Eastern Asia","lat":15.46,"lon":101.07},
  {"code":"BS","code3":"BHS","name":"The Bahamas","region":"Americas","subregion":"Caribbean","lat":26.4,"lon":-77.15},
  {"code":"GM","code3":"GMB","name":"The Gambia","region":"Africa","subregion":"Western Africa","lat":13.64,"lon":-15},
  {"code":"TG","code3":"TGO","name":"Togo","region":"Africa","subregion":"Western Africa","lat":8.81,"lon":1.06},
  {"code":"TO","code3":"TON","name":"Tonga","region":"Oceania","subregion":"Polynesia","lat":-21.21,"lon":-175.16},
  {"code":"TT","code3":"TTO","name":"Trinidad and Tobago","region":"Americas","subregion":"Caribbean","lat":11,"lon":-60.92},
  {"code":"TN","code3":"TUN","name":"Tunisia","region":"Africa","subregion":"Northern Africa","lat":33.69,"lon":9.01},
  {"code":"TR","code3":"TUR","name":"Turkey","region":"Asia","subregion":"Western Asia","lat":39.35,"lon":34.51},
  {"code":"TM","code3":"TKM","name":"Turkmenistan","region":"Asia","subregion":"Central Asia","lat":39.86,"lon":58.68},
  {"code":"TC","code3":"TCA","name":"Turks and Caicos Islands","region":"Americas","subregion":"Caribbean","lat":21.82,"lon":-71.75},
  {"code":"TV","code3":"TUV","name":"Tuvalu","region":"Oceania","subregion":"Polynesia","lat":-8.51,"lon":179.21},
  {"code":"UG","code3":"UGA","name":"Uganda","region":"Africa","subregion":"Eastern Africa","lat":1.97,"lon":32.95},
  {"code":"UA","code3":"UKR","name":"Ukraine","region":"Europe","subregion":"Eastern Europe","lat":49.72,"lon":32.14},
  {"code":"AE","code3":"ARE","name":"United Arab Emirates","region":"Asia","subregion":"Western Asia","lat":23.47,"lon":54.55},
  {"code":"GB","code3":"GBR","name":"United Kingdom","region":"Europe","subregion":"Northern Europe","lat":54.4,"lon":-2.12},
  {"code":"US","code3":"USA","name":"United States of America","region":"Americas","subregion":"Northern America","lat":39.54,"lon":-97.48},
  {"code":"VI","code3":"VIR","name":"United States Virgin Islands","region":"Americas","subregion":"Caribbean","lat":17.75,"lon":-64.78},
  {"code":"UY","code3":"URY","name":"Uruguay","region":"Americas","subregion":"South America","lat":-32.96,"lon":-55.97},
  {"code":"UZ","code3":"UZB","name":"Uzbekistan","region":"Asia","subregion":"Central Asia","lat":41.69,"lon":64.01},
  {"code":"VU","code3":"VUT","name":"Vanuatu","region":"Oceania","subregion":"Melanesia","lat":-15.37,"lon":166.91},
  {"code":"VA","code3":"VAT","name":"Vatican City","region":"Europe","subregion":"Southern Europe","lat":41.9,"lon":12.45},
  {"code":"VE","code3":"VEN","name":"Venezuela","region":"Americas","subregion":"South America","lat":7.18,"lon":-64.6},
  {"code":"VN","code3":"VNM","name":"Vietnam","region":"Asia","subregion":"South-Eastern Asia","lat":21.72,"lon":105.39},
  {"code":"WF","code3":"WLF","name":"Wallis and Futuna","region":"Oceania","subregion":"Polynesia","lat":-14.29,"lon":-178.14},
  {"code":"EH","code3":"ESH","name":"Western Sahara","region":"Africa","subregion":"Northern Africa","lat":23.97,"lon":-12.63},
  {"code":"YE","code3":"YEM","name":"Yemen","region":"Asia","subregion":"Western Asia","lat":15.33,"lon":45.87},
  {"code":"ZM","code3":"ZMB","name":"Zambia","region":"Africa","subregion":"Eastern Africa","lat":-14.66,"lon":26.4},
  {"code":"ZW","code3":"ZWE","name":"Zimbabwe","region":"Africa","subregion":"Eastern Africa","lat":-18.91,"lon":29.93},
]

const BY_CODE = new Map(COUNTRIES.map((country) => [country.code, country]))

/** The country with this ISO alpha-2 code, or undefined. Case-insensitive. */
export function countryByCode(code: string): Country | undefined {
  return BY_CODE.get(code.trim().toUpperCase())
}

/** The language country names are shown in: the page's own (<html lang>), English on the server. */
function pageLanguage(): string {
  return (typeof document !== 'undefined' && document.documentElement.lang) || 'en'
}

const regionNames = new Map<string, Intl.DisplayNames | null>()

/**
 * A country's name in the app's language: countryName('JP') is "日本" on a Japanese page, "Japón" on a Spanish one and
 * "Japan" in English. Show this, not `country.name` (always English), wherever people read a country's name. The
 * names are the browser's own (Intl.DisplayNames); pass `locale` to choose one, e.g. on the server.
 */
export function countryName(country: Country | string, locale: string = pageLanguage()): string {
  const found = typeof country === 'string' ? countryByCode(country) : country
  const code = typeof country === 'string' ? country.trim().toUpperCase() : country.code
  if (/^en\b/i.test(locale) && found) return found.name
  let names = regionNames.get(locale)
  if (names === undefined) {
    try {
      names = new Intl.DisplayNames([locale, 'en'], { type: 'region', fallback: 'none' })
    } catch {
      names = null
    }
    regionNames.set(locale, names)
  }
  let local: string | undefined
  try {
    local = names?.of(code)
  } catch {
    local = undefined
  }
  return local || found?.name || code
}

/** A country's names to match a search against: English and the app's language, lower-cased. */
function namesOf(country: Country, locale: string): string[] {
  const english = country.name.toLowerCase()
  const local = countryName(country, locale).toLocaleLowerCase(locale)
  return local === english ? [english] : [english, local]
}

/**
 * Find a country from whatever the user typed: an ISO code ("JP", "JPN") or a name, in English or in the app's
 * language, exactly, then by prefix, then by any substring. Returns undefined when nothing matches.
 */
export function findCountry(query: string, locale: string = pageLanguage()): Country | undefined {
  const q = query.trim().toLocaleLowerCase(locale)
  if (!q) return undefined
  const upper = q.toUpperCase()
  const exactCode = COUNTRIES.find((c) => c.code === upper || c.code3 === upper)
  if (exactCode) return exactCode
  const named = COUNTRIES.map((country) => ({ country, names: namesOf(country, locale) }))
  return (
    named.find((c) => c.names.some((name) => name === q)) ??
    named.find((c) => c.names.some((name) => name.startsWith(q))) ??
    named.find((c) => c.names.some((name) => name.includes(q)))
  )?.country
}

/** Every country whose name (English or the app's language), code, region or subregion matches — for a search box or a filter list. */
export function searchCountries(query: string, limit = 10, locale: string = pageLanguage()): Country[] {
  const q = query.trim().toLocaleLowerCase(locale)
  if (!q) return []
  const scored = COUNTRIES.map((country) => {
    const names = namesOf(country, locale)
    if (country.code.toLowerCase() === q || country.code3.toLowerCase() === q) return { country, score: 0 }
    if (names.some((name) => name === q)) return { country, score: 1 }
    if (names.some((name) => name.startsWith(q))) return { country, score: 2 }
    if (names.some((name) => name.includes(q))) return { country, score: 3 }
    if (`${country.region} ${country.subregion}`.toLowerCase().includes(q)) return { country, score: 4 }
    return { country, score: Infinity }
  }).filter((entry) => entry.score !== Infinity)
  scored.sort((a, b) => a.score - b.score || countryName(a.country, locale).localeCompare(countryName(b.country, locale), locale))
  return scored.slice(0, limit).map((entry) => entry.country)
}

/** The countries of a UN region or subregion, e.g. countriesIn('Europe') or countriesIn('Western Africa'). */
export function countriesIn(region: string): Country[] {
  const q = region.trim().toLowerCase()
  return COUNTRIES.filter((c) => c.region.toLowerCase() === q || c.subregion.toLowerCase() === q)
}

/** Great-circle distance between two points, in kilometres. */
export function distanceKm(a: { lat: number; lon: number }, b: { lat: number; lon: number }): number {
  const toRad = (deg: number) => (deg * Math.PI) / 180
  const dLat = toRad(b.lat - a.lat)
  const dLon = toRad(b.lon - a.lon)
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLon / 2) ** 2
  return 2 * 6371 * Math.asin(Math.min(1, Math.sqrt(h)))
}
