import assert from 'node:assert/strict';
import test from 'node:test';
import { buildActivityDocument, instantiateTemplateDocument, normalizeCreationProfile } from '@sthstart/contracts';
import type { ContentDocument } from '@sthstart/contracts';
import { ServiceDatabase } from './database.js';
import { ActivityStore } from './activities/store.js';
import { analyzeActivityChanges } from './activities/change-impact.js';
import { listReviewItems, decideReviewItems, startReviewItems } from './activities/review-items.js';
import { rewriteBaseline, applyCandidateSelection, compareCandidate } from './activities/candidate-review.js';
import { SecretStore } from './security.js';
import { createActivityPreset, updateActivityPreset, applySavedActivityTemplate } from './activities/presets.js';
import { getImageConfigDraft, saveImageConfigDraft, commitImageConfigRevision } from './activities/image-configs.js';
function fixture(): ContentDocument {
    const doc = buildActivityDocument({ templateId: 'blank', title: '海边生日会', type: '生日会', theme: '朋友相聚', location: '海边', rules: '', actors: [
            { id: 'a', displayName: '甲', persona: { identity: '寿星' }, activityRole: '寿星', outfitDescription: '白衬衫', appearanceReferenceAssetKeys: [] },
            { id: 'b', displayName: '乙', persona: { identity: '朋友' }, activityRole: '来宾', outfitDescription: '便装', appearanceReferenceAssetKeys: [] },
        ] });
    doc.conversations = [{ id: 'chat', kind: 'group', title: '生日群', memberActorIds: ['a', 'b'] }];
    doc.messages = [1, 2, 3].map(n => ({ id: `m${n}`, kind: 'message', conversationId: 'chat', stageId: doc.stages[0].id, speakerActorId: 'a', text: `消息 ${n}`, storyOrder: n, mediaSlotIds: n === 1 ? ['image'] : [] }));
    doc.mediaSlots = [{ id: 'image', kind: 'image', stageId: doc.stages[0].id, caption: '合照', shotDescription: '海边合照', actorIds: ['a'], sourceFactIds: [] }];
    return doc;
}
function setup(t: test.TestContext) { const db = new ServiceDatabase(); t.after(() => db.close()); const store = new ActivityStore(db); const doc = fixture(); const { activity } = store.createActivity({ title: doc.activity.title, type: doc.activity.type, initialDocument: doc }); return { db, store, doc, id: activity.id }; }
function commit(store: ActivityStore, id: string, doc: ContentDocument) { const draft = store.updateDraft(id, store.getDraft(id)!.draftVersion, doc); return store.commitDraft(id, store.getActivity(id)!.headVersion, draft.draftVersion); }
test('change impact distinguishes wording, appearance and invalid references', () => {
    const before = fixture();
    const wording = structuredClone(before);
    wording.messages[0].text = '生日快乐！';
    assert.deepEqual(analyzeActivityChanges('x', before, wording).map(i => i.targetKind), ['playback']);
    const outfit = structuredClone(before);
    outfit.actors[0].outfitDescription = '礼服';
    assert.deepEqual(analyzeActivityChanges('x', before, outfit).map(i => i.targetKind), ['image']);
    const unrelated = structuredClone(before);
    unrelated.actors[1].outfitDescription = '新衣';
    assert.equal(analyzeActivityChanges('x', before, unrelated).length, 0);
    const removed = structuredClone(before);
    removed.mediaSlots = [];
    assert.ok(analyzeActivityChanges('x', before, removed).some(i => i.targetId === 'm1' && i.severity === 'invalid_reference'));
});
test('review decisions persist, new changes resurface, deferred images never submit', async (t) => {
    const { db, store, doc, id } = setup(t);
    doc.actors[0].outfitDescription = '礼服';
    commit(store, id, doc);
    let item = listReviewItems(db, store, id).find(i => i.targetKind === 'image')!;
    assert.ok(item);
    decideReviewItems(db, store, id, { items: [item], decision: 'keep', expectedHeadVersion: store.getActivity(id)!.headVersion });
    commit(store, id, doc);
    assert.equal(listReviewItems(db, store, id).filter(i => i.decision === 'pending').length, 0);
    doc.actors[0].outfitDescription = '泳装';
    commit(store, id, doc);
    item = listReviewItems(db, store, id).find(i => i.targetKind === 'image' && i.decision === 'pending')!;
    assert.ok(item);
    decideReviewItems(db, store, id, { items: [item], decision: 'rework', expectedHeadVersion: store.getActivity(id)!.headVersion });
    let calls = 0;
    const fetcher: typeof fetch = async () => { calls++; throw new Error('must not connect'); };
    const result = await startReviewItems(db, new SecretStore({}), store, id, { ids: [item.id] }, fetcher);
    assert.equal(calls, 0);
    assert.match(result.results[0].message!, /图片/);
    assert.equal(listReviewItems(db, store, id).find(i => i.id === item.id)!.decision, 'rework');
});
test('partial adoption preserves identity and media; remaining items stay available; retry is idempotent', t => {
    const { db, store, doc, id } = setup(t);
    const candidate = store.createCandidate({ activityId: id, scope: { mode: 'rewrite-records', recordIds: ['m1', 'm2', 'm3'], reviewBaseline: rewriteBaseline(doc, { recordIds: ['m1', 'm2', 'm3'] }) }, payload: { rewrittenMessages: [1, 2, 3].map(n => ({ id: `m${n}`, text: `新消息 ${n}` })) }, validation: {} });
    const apply = (unitIds: string[], key: string) => applyCandidateSelection(db, store, id, candidate.id, { unitIds, idempotencyKey: key, expectedHeadVersion: store.getActivity(id)!.headVersion, expectedDraftVersion: store.getDraft(id)!.draftVersion });
    apply(['rewrite_message:m1', 'rewrite_message:m2'], 'request1');
    assert.deepEqual(store.getDraft(id)!.document.messages[0].mediaSlotIds, ['image']);
    assert.equal(store.getDraft(id)!.document.messages[2].text, '消息 3');
    assert.equal(compareCandidate(db, store, id, candidate.id).units.filter(u => !u.applied && !u.conflict).length, 1);
    const head = store.getActivity(id)!.headVersion;
    apply(['rewrite_message:m1', 'rewrite_message:m2'], 'request1');
    assert.equal(store.getActivity(id)!.headVersion, head);
    assert.throws(() => apply(['rewrite_message:m3'], 'request1'), /相同请求/);
    apply(['rewrite_message:m3'], 'request2');
    assert.ok(store.getCandidate(id, candidate.id)!.adopted);
    assert.equal(store.getDraft(id)!.document.messages[2].text, '新消息 3');
    assert.equal((store.getCandidate(id, candidate.id)!.payload.rewrittenMessages as unknown[]).length, 3);
});
test('one conflicting record aborts the entire selected adoption and locks are checked', t => {
    const { db, store, doc, id } = setup(t);
    const candidate = store.createCandidate({ activityId: id, scope: { mode: 'rewrite-records', recordIds: ['m1', 'm2'], reviewBaseline: rewriteBaseline(doc, { recordIds: ['m1', 'm2'] }) }, payload: { rewrittenMessages: [{ id: 'm1', text: '新1' }, { id: 'm2', text: '新2' }] }, validation: {} });
    doc.messages[1].text = '手工修改';
    commit(store, id, doc);
    assert.throws(() => applyCandidateSelection(db, store, id, candidate.id, { unitIds: ['rewrite_message:m1', 'rewrite_message:m2'], idempotencyKey: 'conflict', expectedHeadVersion: store.getActivity(id)!.headVersion, expectedDraftVersion: store.getDraft(id)!.draftVersion }), /已修改/);
    assert.equal(store.getDraft(id)!.document.messages[0].text, '消息 1');
    doc.editingPolicy = { lockedRecords: [{ kind: 'message', id: 'm1' }], lockedMediaSlotIds: [] };
    commit(store, id, doc);
    assert.match(compareCandidate(db, store, id, candidate.id).units[0].conflict!, /锁定/);
});
test('roles render names consistently, validate missing assignments, and freeze templates', t => {
    const { db, doc } = setup(t);
    const preset = createActivityPreset(db, { kind: 'activity_template', name: '双人生日', payload: { schemaVersion: 2, roleSlots: [{ id: 'lead', label: '寿星', required: true, multiple: false }, { id: 'friends', label: '朋友', required: true, multiple: true }], stages: [{ title: '欢迎 {{role.lead}}', instruction: '{{role.friends}} 带来蛋糕', roleSlotIds: ['lead', 'friends'] }, { title: '合照', roleSlotIds: ['lead', 'friends'] }] } });
    const mappings = { lead: ['a'], friends: ['b'] };
    const direct = instantiateTemplateDocument(doc, preset, mappings);
    const server = applySavedActivityTemplate(db, structuredClone(doc), preset.id, undefined, mappings);
    assert.equal(direct.stages[0].title, server.stages[0].title);
    assert.equal(server.stages[0].instruction, '乙 带来蛋糕');
    assert.deepEqual(server.stages[0].actorIds, ['a', 'b']);
    assert.throws(() => instantiateTemplateDocument(doc, preset, { lead: [], friends: ['b'] }), /请选择/);
    updateActivityPreset(db, preset.id, { payload: { stages: [{ title: '新版' }] } });
    const restored = applySavedActivityTemplate(db, structuredClone(doc), preset.id, server, mappings);
    assert.equal(restored.activity.templateSnapshot!.version, 1);
});
test('creation profile snapshot initializes actual image config; config changes create review items', t => {
    const { db, store, doc, id } = setup(t);
    const preset = createActivityPreset(db, { kind: 'creation_profile', name: '常用', payload: { candidateCount: 2, globalStylePrompt: 'watercolor', globalNegativePrompt: 'bad', expandMedia: false } });
    doc.activity.creationProfile = { presetId: preset.id, name: preset.name, version: preset.version, values: normalizeCreationProfile(preset.payload) };
    commit(store, id, doc);
    updateActivityPreset(db, preset.id, { payload: { globalStylePrompt: 'new' } });
    const draft = getImageConfigDraft(db, id);
    assert.equal(draft.document.globalStylePrompt, 'watercolor');
    const saved = saveImageConfigDraft(db, id, draft.draftVersion, { ...draft.document, globalStylePrompt: 'ink' });
    commitImageConfigRevision(db, store, id, saved.draftVersion, store.getActivity(id)!.headVersion);
    const item = listReviewItems(db, store, id).find(i => i.targetKind === 'image')!;
    assert.ok(item.sourceRefs.some(r => r.kind === 'image_config'));
    decideReviewItems(db, store, id, { items: [item], decision: 'keep', expectedHeadVersion: store.getActivity(id)!.headVersion });
});
test('independent source changes on one image retain both unresolved reasons', t => {
    const { db, store, doc, id } = setup(t);
    doc.actors[0].outfitDescription = '礼服';
    commit(store, id, doc);
    doc.stages[0].location = '室内';
    commit(store, id, doc);
    const item = listReviewItems(db, store, id).find(i => i.targetKind === 'image' && i.decision === 'pending')!;
    assert.deepEqual(new Set(item.sourceRefs.map(r => r.kind)), new Set(['actor', 'stage']));
    decideReviewItems(db, store, id, { items: [item], decision: 'keep', expectedHeadVersion: store.getActivity(id)!.headVersion });
});
test('project import remaps frozen roles and restores partial candidate progress without restarting jobs', async (t) => {
    const { mkdtempSync, rmSync } = await import('node:fs');
    const { tmpdir } = await import('node:os');
    const { join } = await import('node:path');
    const { readConfig } = await import('./config.js');
    const { buildActivityExportPackage } = await import('./activities/exports.js');
    const { stageActivityImport, commitActivityImport } = await import('./activities/imports.js');
    const root = mkdtempSync(join(tmpdir(), 'rework-roundtrip-'));
    t.after(() => rmSync(root, { recursive: true, force: true }));
    const config = readConfig({ STHSTART_ARTIFACT_DIR: root });
    config.artifactDirectory = root;
    const { db, store, doc, id } = setup(t);
    doc.activity.templateSnapshot = { presetId: 'deleted-template', name: '双人模板', version: 1, payload: { roleSlots: [{ id: 'lead', label: '寿星' }] }, actorMappings: { lead: ['a'] } };
    doc.activity.birthdayActorIds = ['a'];
    doc.activity.creationProfile = { name: '旧配置', version: 2, values: normalizeCreationProfile({ candidateCount: 3 }) };
    commit(store, id, doc);
    const candidate = store.createCandidate({ activityId: id, scope: { mode: 'rewrite-records', recordIds: ['m1', 'm2'], reviewBaseline: rewriteBaseline(doc, { recordIds: ['m1', 'm2'] }) }, payload: { rewrittenMessages: [{ id: 'm1', text: '已采用内容' }, { id: 'm2', text: '待采用内容' }] }, validation: {} });
    applyCandidateSelection(db, store, id, candidate.id, { unitIds: ['rewrite_message:m1'], idempotencyKey: 'export1', expectedHeadVersion: store.getActivity(id)!.headVersion, expectedDraftVersion: store.getDraft(id)!.draftVersion });
    const bytes = await buildActivityExportPackage(config, db, store, id, { format: 'project' });
    const staged = await stageActivityImport(config, db, bytes);
    const imported = await commitActivityImport(config, db, store, staged.jobId);
    const fresh = store.getDraft(imported.activity.id)!.document;
    assert.notEqual(fresh.actors[0].id, 'a');
    assert.deepEqual(fresh.activity.templateSnapshot!.actorMappings!.lead, [fresh.actors[0].id]);
    assert.deepEqual(fresh.activity.birthdayActorIds, [fresh.actors[0].id]);
    assert.equal((fresh.activity.creationProfile!.values as {
        candidateCount: number;
    }).candidateCount, 3);
    const newCandidate = store.listCandidates(imported.activity.id)[0];
    const comparison = compareCandidate(db, store, imported.activity.id, newCandidate.id);
    assert.equal(comparison.units.filter(u => u.applied).length, 1);
    assert.equal(comparison.units.filter(u => !u.applied && !u.conflict).length, 1);
    const remaining = comparison.units.find(u => !u.applied)!;
    applyCandidateSelection(db, store, imported.activity.id, newCandidate.id, { unitIds: [remaining.id], idempotencyKey: 'import1', expectedHeadVersion: 1, expectedDraftVersion: 1 });
    assert.equal(store.getDraft(imported.activity.id)!.document.messages[1].text, '待采用内容');
    assert.equal(db.connection.prepare("SELECT COUNT(*) n FROM activity_jobs WHERE activity_id=? AND status IN ('queued','running')").get(imported.activity.id)!.n, 0);
});
test('later candidates require their exact adopted predecessors', async (t) => {
    const { assertCandidateDependencies, recordWholeApplication } = await import('./activities/candidate-review.js');
    const { db, store, doc, id } = setup(t);
    const first = store.createCandidate({ activityId: id, scope: { mode: 'stage', stageId: doc.stages[0].id }, payload: {}, validation: {} });
    const later = store.createCandidate({ activityId: id, scope: { mode: 'stage', stageId: doc.stages[1].id, precedingCandidateIds: [first.id] }, payload: {}, validation: {} });
    assert.throws(() => assertCandidateDependencies(db, store, id, later.id), /前序/);
    assert.doesNotThrow(() => assertCandidateDependencies(db, store, id, later.id, [first.id, later.id]));
    db.connection.prepare('UPDATE activity_candidates SET adopted=1 WHERE id=?').run(first.id);
    recordWholeApplication(db, id, first.id, doc, doc.stages[0].id, store.getActivity(id)!.currentContentRevisionId!);
    assert.doesNotThrow(() => assertCandidateDependencies(db, store, id, later.id));
    doc.messages[0].text = '改过的前序';
    commit(store, id, doc);
    assert.throws(() => assertCandidateDependencies(db, store, id, later.id), /又发生了变化/);
});
test('appearance-only persona changes affect images, and manual corrections remain actionable', t => {
    const { db, store, doc, id } = setup(t);
    const changed = structuredClone(doc);
    changed.actors[0].persona.appearance = { hair: 'gold' };
    assert.deepEqual(analyzeActivityChanges(id, doc, changed).map(i => i.targetKind), ['image']);
    doc.actors[0].persona.identity = '更开朗的寿星';
    commit(store, id, doc);
    doc.messages[0].text = '手工修订后的发言';
    commit(store, id, doc);
    const item = listReviewItems(db, store, id).find(i => i.targetId === 'm1' && i.decision === 'pending')!;
    decideReviewItems(db, store, id, { items: [item], decision: 'keep', expectedHeadVersion: store.getActivity(id)!.headVersion });
});
test('repairing a broken media reference resolves the invalid item', t => {
    const { db, store, doc, id } = setup(t);
    doc.mediaSlots = [];
    commit(store, id, doc);
    const broken = listReviewItems(db, store, id).find(i => i.severity === 'invalid_reference')!;
    assert.ok(broken);
    assert.throws(() => decideReviewItems(db, store, id, { items: [broken], decision: 'keep', expectedHeadVersion: store.getActivity(id)!.headVersion }), /引用已失效/);
    doc.messages[0].mediaSlotIds = [];
    commit(store, id, doc);
    assert.equal(listReviewItems(db, store, id).find(i => i.id === broken.id)!.decision, 'resolved');
});
test('successful text job resolves its rework item only when its candidate is adopted', t => {
    const { db, store, doc, id } = setup(t);
    doc.actors[0].persona.identity = '热情的寿星';
    commit(store, id, doc);
    const item = listReviewItems(db, store, id).find(i => i.targetId === 'm1' && i.decision === 'pending')!;
    decideReviewItems(db, store, id, { items: [item], decision: 'rework', expectedHeadVersion: store.getActivity(id)!.headVersion });
    const candidate = store.createCandidate({ activityId: id, scope: { mode: 'rewrite-records', recordIds: ['m1'], reviewBaseline: rewriteBaseline(doc, { recordIds: ['m1'] }) }, payload: { rewrittenMessages: [{ id: 'm1', text: '欢迎大家来我的生日会！' }] }, validation: {} });
    const now = new Date().toISOString();
    db.connection.prepare("INSERT INTO activity_jobs(id,activity_id,kind,mode,status,request_hash,result_candidate_ids_json,created_at,updated_at) VALUES('rework-job',?,'text','rewrite-records','succeeded','test',?,?,?)").run(id, JSON.stringify([candidate.id]), now, now);
    db.connection.prepare('UPDATE activity_review_items SET execution_json=? WHERE id=?').run(JSON.stringify({ kind: 'text', id: 'rework-job' }), item.id);
    assert.equal(listReviewItems(db, store, id).find(i => i.id === item.id)!.decision, 'rework');
    applyCandidateSelection(db, store, id, candidate.id, { unitIds: ['rewrite_message:m1'], expectedHeadVersion: store.getActivity(id)!.headVersion, expectedDraftVersion: store.getDraft(id)!.draftVersion, idempotencyKey: 'finish-rework' });
    assert.ok(listReviewItems(db, store, id).filter(i => i.targetId === 'm1').every(i => i.decision === 'resolved'));
});
test('applying a creation profile updates content and image settings together with version checks', async (t) => {
    const { createService } = await import('./server.js');
    const { readConfig } = await import('./config.js');
    const db = new ServiceDatabase();
    const store = new ActivityStore(db);
    const token = 'rework-profile-test-token-123456789';
    const { app } = await createService({ database: db, config: readConfig({ STHSTART_ADMIN_TOKEN: token }), secrets: new SecretStore({}) });
    t.after(async () => { await app.close(); db.close(); });
    const doc = fixture();
    const { activity, draft } = store.createActivity({ title: doc.activity.title, type: doc.activity.type, initialDocument: doc });
    const preset = createActivityPreset(db, { kind: 'creation_profile', name: '水彩', payload: { textMode: 'whole-text', candidateCount: 2, globalStylePrompt: 'watercolor' } });
    const path = `/api/v1/admin/activities/${activity.id}/creation-profile/apply`;
    const headers = { 'x-sthstart-admin-token': token };
    const response = await app.inject({ method: 'POST', url: path, headers, payload: { presetId: preset.id, presetVersion: preset.version, expectedHeadVersion: activity.headVersion, expectedDraftVersion: draft.draftVersion } });
    assert.equal(response.statusCode, 200, response.body);
    assert.equal(getImageConfigDraft(db, activity.id).document.globalStylePrompt, 'watercolor');
    assert.deepEqual(store.getDraft(activity.id)!.document.messages, doc.messages);
    assert.equal((store.getDraft(activity.id)!.document.activity.creationProfile!.values as {
        textMode: string;
    }).textMode, 'whole-text');
    const head = store.getActivity(activity.id)!.headVersion;
    updateActivityPreset(db, preset.id, { name: '新版水彩' });
    const stale = await app.inject({ method: 'POST', url: path, headers, payload: { presetId: preset.id, presetVersion: preset.version, expectedHeadVersion: head, expectedDraftVersion: store.getDraft(activity.id)!.draftVersion } });
    assert.equal(stale.statusCode, 409);
    assert.equal(store.getActivity(activity.id)!.headVersion, head);
    const cleared = await app.inject({ method: 'POST', url: path, headers, payload: { presetId: null, presetVersion: 0, expectedHeadVersion: head, expectedDraftVersion: store.getDraft(activity.id)!.draftVersion } });
    assert.equal(cleared.statusCode, 200, cleared.body);
    assert.equal(store.getDraft(activity.id)!.document.activity.creationProfile, undefined);
});
